### ISSUE TITLE
app stops after every screenshot

### ISSUE THREAD

**Issue by kidney-bean** [cvzi/ScreenshotTile#100]
every time I take a screenshot, the app stops before the notification shows. it's annoying because to edit the screenshot, I need to open the camera after every screenshot and find the screenshot instead of just clicking the notification. I am using Android 7, rooted with magisk, has Xposed. Samsung note 5

**Comment by cvzi** [comment]
Thanks for the report! I have created a version with a temporary fix. It will probably be released in the next few days.
See issue #98

**Comment by cvzi** [comment]
Should be fixed now
