### ISSUE TITLE
Floating button always uses Native method (regardless of setting) when floating button action is set to "Take a screenshot", but not when action "Select area" is set.

### ISSUE THREAD

**Issue by DanielKonopka** [cvzi/ScreenshotTile#117]
Floating button always uses Native method (regardless of setting) for taking screenshots when floating button action is set to "Take a screenshot", but **not** when action "Select area" is set.

OS: Android 10
EMUI: 10.1.1

**Comment by cvzi** [comment]
It is now possible to select "original method" or "native method" in the app settings for the floating button action
