### ISSUE TITLE
Data loss while using the app (dialog disappears after on-screen rotation)

### ISSUE THREAD

**Issue by davirec** [cvzi/ScreenshotTile#119]
When I perform these sequences of events, the dialog disappears after on-screen rotation:
1. Go to the Main activity
2. Tap in More Settings
3. Tap in Floating button theme
4. A fragment similar to this will appear:

Before rotation:
<img src="https://user-images.githubusercontent.com/3637419/158002015-5a2eabf9-3ade-4963-9fcc-1ec3f8d7d8e7.png" width=30% height=30%>

5. Force the pause from the activity and then return to the activity (double rotation). Note that the fragment disappears. 

Note: the pause from activity can be performed in several ways. We suggest using a double rotation (starts in portrait, goes to landscape, and back to portrait) with this function previously enabled in the smartphone.

The expected behavior is the return to the previous state with the fragments of the previous image.

However, the fragment disappears.

After rotation:
<img src="https://user-images.githubusercontent.com/3637419/158002012-66336ba7-4cbb-4de7-b7c3-3a605d11e613.png" width=30% height=30%>

Device:
- Device: Moto G30 with OS: Android 11
- Version: 1.14.10
- Device language: English

**Comment by cvzi** [comment]
Thanks for the thorough description. I have no idea how to fix this, but I will try to find out

**Comment by cvzi** [comment]
Should be fixed in next version v1.14.11

**Comment by davirec** [comment]
Hi, cvzi.
In this activity, we found other bugs: 

<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147961-f763d58b-29ba-451a-bd75-45d215effeb5.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147960-3e27c2c9-1871-4fdf-9bdf-e0ed87b20550.png" width=20% height=20%>
</figure>

</div> 


<div id="ladoalado" style="display:flex;justify-content:center;">

<figure id="container">Before and after double screen rotation<br>
<img src="https://user-images.githubusercontent.com/3637419/159147981-82b0c828-f3a7-49ca-a6d1-881963a040e9.png" width=20% height=20% >
</figure>

<figure id="container">
<img src="https://user-images.githubusercontent.com/3637419/159147983-759fb8f0-5fba-472b-8a21-f5a02823aa70.png" width=20% height=20%>
</figure>

</div> 

Note:

- Double screen rotation: It is executed twice to reach a state that should be exactly the same as the screen before if no data loss occurred.
- A data loss problem occurs when data is accidentally deleted or state variables are accidentally assigned with default or initial values.

**Comment by cvzi** [comment]
I think this has something to do with the onPause()/onResume() methods in the Android activity

**Comment by cvzi** [comment]
Implemented in [v1.16.1](https://github.com/cvzi/ScreenshotTile/releases/tag/v1.16.1)
