### ISSUE TITLE
Freeze when requiring storage permission

### ISSUE THREAD

**Issue by linsui** [cvzi/ScreenshotTile#13]
When it requires storage permission, it freezes.;

![Screenshot_20190901-110153](https://user-images.githubusercontent.com/36977733/64071240-5c12a600-cc65-11e9-9dac-f5a6f729e7dd.png)

**Comment by cvzi** [comment]
Thanks for the report.
Does it happen every time?
Which Android version is your phone?

**Comment by linsui** [comment]
It happens every time. I can grante permissions manully. My rom is AOSP 9.

**Comment by cvzi** [comment]
Has this happened with earlier app versions as well or only on the newest version?

**Comment by linsui** [comment]
1.5.3 works but 1.5.4 has this problem.

**Comment by cvzi** [comment]
Okay thanks. I will investigate.
