### ISSUE TITLE
Custom image quality

### ISSUE THREAD

**Issue by wankio** [cvzi/ScreenshotTile#175]
I see there is no opacity settings in app, i think it should have it

**Comment by cvzi** [comment]
The button is already a little transparent.
I can add an option to make it more transparent, but not to make it more opaque

**Comment by wankio** [comment]
Yeah, custom theme for button would be great

**Comment by wankio** [comment]
and quality encode, have custom input number for quality would be good, because i think 70% webp is not so good, i tested many times on PC, jpg 86% is the best, but dont know about webp

**Comment by cvzi** [comment]
The current version [v1.18.0](https://github.com/cvzi/ScreenshotTile/releases/tag/v1.18.0) now has an option to change the opacity. It is currently in the advanced options (in the app options scroll down to the bottom, there is a "advanced options" button). I may move it to the normal options later. You can set a value from `1.0` (opaque) to `0.0` (fully-transparent).
