### ISSUE TITLE
Home Button Shot Not Working

### ISSUE THREAD

**Issue by rjm831** [cvzi/ScreenshotTile#191]
Using a Samsung Tab A7.  Samsung just updated to Android 12 and the app no longer functions with Native/Assist.  When I long press the home button the screen turns blank and in the color of the app, and completely freezes.  I don't know if this bug is due to recent app updates or due to Samsung's Android 12 upgrade.  Don't have root privileges but will provide any logs or data if needed.

**Comment by cvzi** [comment]
I don't think I have changed something in that respect with the last updates, but if you want you can try an older version from:
https://github.com/cvzi/ScreenshotTile/releases
Or from F-Droid:
https://f-droid.org/packages/com.github.cvzi.screenshottile/
(you have to uninstall the app first, because Android does not allow downgrading) 

If you know how to access the logs on Android, the logs would probably help me. I have attached a "debug" version 
screenshottile_72-debug.apk  to the release here: https://github.com/cvzi/ScreenshotTile/releases/tag/v1.18.3
That version writes more information to the logs, so if you could install the apk file and test the home button and then retrieve the logs, that would be ideal. 


El 10 de agosto de 2022 16:13:02 CEST, Ronald Jessie McLaren ***@***.***> escribió:
>Using a Samsung Tab A7.  Samsung just updated to Android 12 and the app no longer functions with Native/Assist.  When I long press the home button the screen turns blank and in the color of the app, and completely freezes.  I don't know if this bug is due to recent app updates or due to Samsung's Android 12 upgrade.  Don't have root privileges but will provide any logs or data if needed.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/cvzi/ScreenshotTile/issues/191
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by rjm831** [comment]
--------- beginning of main
V/ToastPresenter(23289): Text: Sead in ***@***.***
***@***.***[Toast](23289): setView = ***@***.*** TM=true
***@***.***[Toast](23289): Relayout returned: old=(0,36,2000,1128) new=(821,970,1179,1032) req=(358,62)0 dur=5 res=0x7 s={true 542616350720} ch=true fn=-1
***@***.***[Toast](23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[Toast](23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): [DP] rdf()
***@***.***[Toast](23289): reportDrawFinished (fn: -1) 
***@***.***[Toast](23289): dispatchDetachedFromWindow
D/InputTransport(23289): Input channel destroyed: 'fa1d21b', fd=100
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)0 dur=6 res=0x1 s={true 540563542016} ch=false fn=14
I/AssistStructure(23289): Flattened final assist data: 5424 bytes, containing 2 windows, 42 views
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=88
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_STATUS_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(23289): startInputInner - Id : 0
I/InputMethodManager(23289): startInputInner - mService.startInputOrWindowGainedFocus

--------- beginning of main
***@***.***[Toast](23289): setView = ***@***.*** TM=true
***@***.***[Toast](23289): Relayout returned: old=(0,36,2000,1128) new=(821,970,1179,1032) req=(358,62)0 dur=5 res=0x7 s={true 540564418560} ch=true fn=-1
***@***.***[Toast](23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[Toast](23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): [DP] rdf()
***@***.***[Toast](23289): reportDrawFinished (fn: -1) 
***@***.***[Toast](23289): dispatchDetachedFromWindow
D/InputTransport(23289): Input channel destroyed: 'ce11a3 ', fd=110
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)0 dur=5 res=0x1 s={true 540563759104} ch=false fn=30
I/AssistStructure(23289): Flattened final assist data: 5260 bytes, containing 2 windows, 41 views
D/AbsListView(23289):  in onLayout changed 
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=87
***@***.******@***.***(23289): handleAppVisibility mAppVisible=true visible=false
***@***.******@***.***(23289): Relayout returned: old=(948,8,1052,37) new=(948,8,1052,37) req=(104,29)8 dur=7 res=0x5 s={false 0} ch=true fn=3
***@***.***[LogActivity](23289): handleAppVisibility mAppVisible=true visible=false
***@***.******@***.***(23289): stopped(true) old=false
***@***.***[LogActivity](23289): stopped(true) old=false
***@***.******@***.***(23289): dispatchDetachedFromWindow
D/InputTransport(23289): Input channel destroyed: 'c82a648', fd=72
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)8 dur=7 res=0x5 s={false 0} ch=false fn=-1
***@***.***[LogActivity](23289): handleAppVisibility mAppVisible=false visible=true
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)4 dur=5 res=0x1 s={false 0} ch=false fn=-1
***@***.***[LogActivity](23289): stopped(false) old=true
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=76
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=103
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=104
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=98
D/InputTransport(23289): Input channel destroyed: 'ClientS', fd=94
***@***.******@***.***(23289): setView = ***@***.*** TM=true
***@***.******@***.***(23289): stopped(false) old=false
***@***.***[LogActivity](23289): stopped(false) old=false
V/Toast   (23289): show: caller = org.jtb.alogcat.LogActivity.reset:244 
V/Toast   (23289): show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
V/Toast   (23289): show: isActivityContext = true
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)0 dur=18 res=0x7 s={true 542617849856} ch=true fn=-1
D/AbsListView(23289):  in onLayout changed 
***@***.***[LogActivity](23289): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[LogActivity](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[LogActivity](23289): [DP] pdf(0) 1 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[LogActivity](23289): [DP] rdf()
***@***.***[LogActivity](23289): reportDrawFinished (fn: -1) 
***@***.******@***.***(23289): Resizing ***@***.***: frame=[948,44][1052,73] reportDraw=true forceLayout=false backDropFrame=Rect(0, 0 - 104, 29)
***@***.******@***.***(23289): Relayout returned: old=(0,36,2000,1128) new=(948,44,1052,73) req=(104,29)0 dur=20 res=0x7 s={true 542617878528} ch=true fn=-1
***@***.******@***.***(23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.******@***.***(23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.******@***.***(23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.******@***.***(23289): [DP] rdf()
***@***.******@***.***(23289): reportDrawFinished (fn: -1) 
V/ToastPresenter(23289): Text: Sead in ***@***.***
***@***.***[Toast](23289): setView = ***@***.*** TM=true
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_STATUS_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
***@***.***[Toast](23289): Resizing ***@***.***: frame=[821,970][1179,1032] reportDraw=true forceLayout=false backDropFrame=Rect(0, 0 - 358, 62)
***@***.***[Toast](23289): Relayout returned: old=(0,36,2000,1128) new=(821,970,1179,1032) req=(358,62)0 dur=11 res=0x7 s={true 542617886720} ch=true fn=-1
***@***.***[Toast](23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[Toast](23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): [DP] rdf()
***@***.***[Toast](23289): reportDrawFinished (fn: -1) 
***@***.******@***.***(23289): handleResized, msg = 5 frames=ClientWindowFrames{frame=[948,44][1052,73] display=[0,36][2000,1128] backdrop=[0,0][104,29]} forceNextWindowRelayout=false displayId=0 frameChanged=false backdropFrameChanged=true configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={1.1 ?mcc?mnc [en_US] ldltr sw800dp w1333dp h728dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1128) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.414 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0} mOverrideConfig={1.1 ?mcc?mnc [en_US] ldltr sw800dp w1333dp h728dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1128) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=standard mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.3 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0}}
***@***.******@***.***(23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.handleResized:2222 android.view.ViewRootImpl.access$1200:294 
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(23289): startInputInner - Id : 0
I/InputMethodManager(23289): startInputInner - mService.startInputOrWindowGainedFocus
***@***.***[Toast](23289): handleResized, msg = 5 frames=ClientWindowFrames{frame=[821,970][1179,1032] display=[0,0][2000,1128] backdrop=[0,0][358,62]} forceNextWindowRelayout=false displayId=0 frameChanged=false backdropFrameChanged=true configChanged=false displayChanged=false mNextDrawUseBlastSync=false mergedConfiguration={mGlobalConfig={1.1 ?mcc?mnc [en_US] ldltr sw800dp w1333dp h728dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1128) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=off mFreeformTaskPinningState=unpinned} s.414 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0} mOverrideConfig={1.1 ?mcc?mnc [en_US] ldltr sw800dp w1333dp h728dp 240dpi xlrg land finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2000, 1200) mAppBounds=Rect(0, 0 - 2000, 1128) mMaxBounds=Rect(0, 0 - 2000, 1200) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_90 mPopOver=undefined mFreeformTaskPinningState=undefined} s.414 fontWeightAdjustment=0 ff=0 bf=0 bts=0 enb/d themeSeq=0}}
***@***.***[Toast](23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.handleResized:2222 android.view.ViewRootImpl.access$1200:294 
***@***.***[Toast](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[Toast](23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): [DP] rdf()
***@***.***[Toast](23289): reportDrawFinished (fn: -1) 
***@***.******@***.***(23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.******@***.***(23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.******@***.***(23289): [DP] rdf()
***@***.******@***.***(23289): reportDrawFinished (fn: -1) 
D/InputMethodManager(23289): startInputInner - Id : 0
I/InputMethodManager(23289): startInputInner - mService.startInputOrWindowGainedFocus
***@***.***[Toast](23289): dispatchDetachedFromWindow
D/InputTransport(23289): Input channel destroyed: '2a9de8c', fd=82

--------- beginning of main
V/Toast   (23289): show: caller = org.jtb.alogcat.LogActivity.reset:244 
V/Toast   (23289): show: focusDisplayId = 0, isFocusInDesktop = false mCustomDisplayId=-1 isDexDualMode=false
V/Toast   (23289): show: isActivityContext = true
V/ToastPresenter(23289): Text: Sead in ***@***.***
***@***.***[Toast](23289): setView = ***@***.*** TM=true
***@***.***[Toast](23289): Relayout returned: old=(0,36,2000,1128) new=(821,970,1179,1032) req=(358,62)0 dur=5 res=0x7 s={true 542369427456} ch=true fn=-1
***@***.***[Toast](23289): [DP] dp(1) 0 android.view.ViewRootImpl.reportNextDraw:11410 android.view.ViewRootImpl.performTraversals:4185 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): Creating frameDrawingCallback nextDrawUseBlastSync=false reportNextDraw=true hasBlurUpdates=false
***@***.***[Toast](23289): [DP] pdf(0) 0 android.view.ViewRootImpl.performDraw:5199 android.view.ViewRootImpl.performTraversals:4204 android.view.ViewRootImpl.doTraversal:2911 
***@***.***[Toast](23289): [DP] rdf()
***@***.***[Toast](23289): reportDrawFinished (fn: -1) 
***@***.***[Toast](23289): dispatchDetachedFromWindow
D/InputTransport(23289): Input channel destroyed: '5d2da8 ', fd=100
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
***@***.***[LogActivity](23289): ViewPostIme pointer 0
***@***.***[LogActivity](23289): ViewPostIme pointer 1
I/DecorView(23289): notifyKeepScreenOnChanged: keepScreenOn=false
***@***.***[LogActivity](23289): Relayout returned: old=(0,0,2000,1200) new=(0,0,2000,1200) req=(2000,1200)0 dur=5 res=0x1 s={true 545668067328} ch=false fn=19
D/SmartClipDataCropperImpl(23289): doExtractSmartClipData : Extraction start! reqId = 6  Cropped area = Rect(1000, 600 - 1001, 601)  Package = org.jtb.alogcat
D/SmartClipDataCropperImpl(23289): addAppMetaTag : package name is org.jtb.alogcat
D/SmartClipDataCropperImpl(23289): sendExtractionResultToSmartClipService : -- Extracted SmartClip data information --
D/SmartClipDataCropperImpl(23289): sendExtractionResultToSmartClipService : Request Id : 6
D/SmartClipDataCropperImpl(23289): sendExtractionResultToSmartClipService : Extraction mode : 1
D/SemSmartClipDataRepository(23289): ----- Start of SmartClip repository informations -----
D/SemSmartClipDataRepository(23289): ** Content type : image
D/SemSmartClipDataRepository(23289): ** Meta area rect : Rect(0, 0 - 0, 0)
D/SemSmartClipDataRepository(23289): ** Captured image file path : null
D/SemSmartClipDataRepository(23289): ----- End of SmartClip repository informations -----
D/SmartClipDataCropperImpl(23289): sendExtractionResultToSmartClipService : Elapsed = 4
D/SmartClipRemoteRequestDispatcher(23289): dispatchScrollableAreaInfo : windowRect = Rect(0, 0 - 2000, 1200)
D/SmartClipRemoteRequestDispatcher(23289): dispatchScrollableAreaInfo : Scrollable view count = 1
D/SmartClipRemoteRequestDispatcher(23289): dispatchScrollableAreaInfo : Unscrollable view count = 0
D/SmartClipRemoteRequestDispatcher(23289): dispatchScrollableAreaInfo : Pkg=org.jtb.alogcat Activity=null
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_NAVIGATION_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
D/InsetsSourceConsumer(23289): ensureControlAlpha: for ITYPE_STATUS_BAR on org.jtb.alogcat/org.jtb.alogcat.LogActivity
***@***.***[LogActivity](23289): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(23289): startInputInner - Id : 0
I/InputMethodManager(23289): startInputInner - mService.startInputOrWindowGainedFocus

**Comment by cvzi** [comment]
Thanks. I don't see anything relating to the app at all, which is strange. 

I checked the aLogcat app, and it seems that app doesn't work on newer Android versions. It only shows logs from the Android system and from aLogcat itself, not from other apps.

You would have to use a computer with the Android SDK Platform Tools installed and run `adb logcat` to get the full log via USB.


I will try the app myself on an Android 12 device later, I currently don't have access to one. But I am pretty sure I checked it on Android 12 the last time I made major changes, so I doubt I'll find anything. It's probably related to your specific device or Samsung.

**Comment by rjm831** [comment]
Thanks for checking.  I'm sure its specific to the Samsung upgrade; its really strange that the debug apk works but the regular app doesn't.   Unfortunately I don't have access to a computer for the ADB or I'd certainly offer the logcat.  If I can be of help in any other way just drop me an email. Thanks again for the help, and for the app itself.  I honestly appreciate the time and energy involved.-Jessie2:15 PM, August 10, 2022, cvzi ***@***.***>:
Thanks. I don't see anything relating to the app at all, which is strange.
I checked the aLogcat app, and it seems that app doesn't work on newer Android versions. It only shows logs from the Android system and from aLogcat itself, not from other apps.
You would have to use a computer with the Android SDK Platform Tools installed and run adb logcat to get the full log via USB.
I will try the app myself on an Android 12 device later, I currently don't have access to one. But I am pretty sure I checked it on Android 12 the last time I made major changes, so I doubt I'll find anything. It's probably related to your specific device or Samsung.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by cvzi** [comment]
I see, that's a bit unexpected that the debug version works. Since you never had the debug version installed, the debug app started with a fresh settings copy. Maybe the settings or something else got corrupted during the update of Android or during the update of the app and that's causing the crash.

Find the app in the Android settings in the "Apps" section. There you can "Force stop" the app and then tap on "Storage and cache" and then "Clear storage". Then open the app and set it as assistant again and make sure the app settings are as you want them.
Or you could try uninstalling the app, restarting the phone and the re-install the app.

Also you could definitely keep using the debug version, there's no harm in using it, you just won't get app updates.

**Comment by rjm831** [comment]
Hope these logcats help.  Really weird thing:  the debug apk works fine and the regular app doesn't!  Older versions have the same problem so I suspect the issue is specific to Samsung's Android 12 upgrade - maybe the accessibility module has a bug.In any case, the latest debug version actually works using the home button.  I will happily help you with whatever I can do if you want to explore this issue.  I'm a noob and don't have root, and the logcat app I'm using isn't great, but I'm thankful to you for the development so please ask for whatever you need.- R Jessie McLarenSanta Cruz, CA7:26 AM, August 10, 2022, cvzi ***@***.***>:
I don't think I have changed something in that respect with the last updates, but if you want you can try an older version from:
https://github.com/cvzi/ScreenshotTile/releases
Or from F-Droid:
https://f-droid.org/packages/com.github.cvzi.screenshottile/
(you have to uninstall the app first, because Android does not allow downgrading) 

If you know how to access the logs on Android, the logs would probably help me. I have attached a "debug" version 
screenshottile_72-debug.apk  to the release here: https://github.com/cvzi/ScreenshotTile/releases/tag/v1.18.3
That version writes more information to the logs, so if you could install the apk file and test the home button and then retrieve the logs, that would be ideal. 


El 10 de agosto de 2022 16:13:02 CEST, Ronald Jessie McLaren ***@***.***> escribió:
>Using a Samsung Tab A7.  Samsung just updated to Android 12 and the app no longer functions with Native/Assist.  When I long press the home button the screen turns blank and in the color of the app, and completely freezes.  I don't know if this bug is due to recent app updates or due to Samsung's Android 12 upgrade.  Don't have root privileges but will provide any logs or data if needed.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/cvzi/ScreenshotTile/issues/191
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Sent from Yandex Mail for mobile

**Comment by cvzi** [comment]
I don't know what could be the problem. My knowledge of the difference between debug and release version in Android is limited.

When I publish the next version of the app, I can create another debug version for you to see if that will work as well.

**Comment by cvzi** [comment]
Here is the debug version of the latest release:
https://github.com/cvzi/ScreenshotTile/releases/download/v2.0.0/screenshottile_83-debug.apk
