### ISSUE TITLE
Option to disable Screenshot History

### ISSUE THREAD

**Issue by rjm831** [cvzi/ScreenshotTile#206]
Please consider an option to disable this function in the new beta; I've privacy issues with it.  Don't want a history being kept at all, despite having an option to erase.  Thanks, and thanks for continuing this development.

**Comment by cvzi** [comment]
In the newest version there is a switch in the history screen to disable it, and there is also a switch in the settings under the advanced settings.

**Comment by rjm831** [comment]
Thank you!
