### ISSUE TITLE
Color and opacity of floating button

### ISSUE THREAD

**Issue by Rudde** [cvzi/ScreenshotTile#215]
The button already have two different themes and you can adjust its size. Unfortunately the themes are very similar and I've experienced the button blending into some of my apps. I would be very applicative of an option to change the color of it, and maybe change the opacity from 100% and down to maybe 10% would also be nice.

**Comment by cvzi** [comment]
The opacity can be changed, the setting is kind of hidden tough. It is currently in the advanced settings. 
The themes are essentially SVG images, so it should be easy enough to change the color of the images and add new images, or maybe it is possible to change the color during runtime, I don't know, I'll check it out.

For better usability the settings for the floating button should be grouped together or there should be an extra settings screen for the floating button 🤨

**Comment by Rudde** [comment]
Thank you, I found the opacity setting. I see it was already at 100% despite the button not being solid. I suspect it might have opacity defined in the SVG too maybe? Since there is a setting maybe it should override whatever the SVG says so setting opacity to 1.0 will result in a solid floating button? Or else I see no other option of accomplishing this?

**Comment by cvzi** [comment]
You're right, the image already has transparent colors, I didn't think to remove that when I added the transparency option.
