### ISSUE TITLE
Launcher icon

### ISSUE THREAD

**Issue by JonnyTech** [cvzi/ScreenshotTile#25]
When the option to `Hide app icon from launcher` is enabled, the icon remains visible in the launcher and clicking on it pops up a toast message stating `App uninstalled.`.

**Comment by cvzi** [comment]
Thanks for the report. Which launcher do you use (or phone model, if you're using the standard launcher)?
I just tested a few on several emulators and it still seems to work fine for me. It looks like some launchers (e.g. Nova) require several minutes (or a reboot) to update the icons.

**Comment by JonnyTech** [comment]
Using [OpenLauncher](https://github.com/openlauncherteam/openlauncher/) on [AOSP 10 GSI](https://github.com/phhusson/treble_experimentations/). Just tried with built-in QuickStep launcher and the icon remains too. Clicking on it when set to hidden takes me to the settings App Info page for the app. No change after a reboot. Would you like me to try something else?

**Comment by cvzi** [comment]
Looks like manually hiding an icon is no longer supported on Android 10 😪
It's only possible if the app is already "hidden" on install or does not require any permissions ([android reference](https://developer.android.com/reference/android/content/pm/LauncherApps#getActivityList(java.lang.String,%20android.os.UserHandle)))

I guess I'll then remove the option on Android 10

**Comment by JonnyTech** [comment]
Another app was able to hide its icon and works on Android 10 ([Suntimes](https://github.com/forrestguice/SuntimesWidget/issues/305)). Maybe the related [commit](https://github.com/forrestguice/SuntimesWidget/commit/bcde83138f62f7888ed7cb255a7c01075c5c7183) may help.

**Comment by cvzi** [comment]
Thanks, at first glance that commit looks to be the same code as I am using. I'll try around on an emulator with Android 10 when I have some more time. 
I might be that we can still hide icons but only if there are multiple icons for one app

**Comment by cvzi** [comment]
For now I removed the setting for Android 10.

It seems like removing all icons of an app is only possible if the app uses no permissions.
Otherwise at least one icon remains visible, which is a dummy icon that opens the "app setting screen" where you can uninstall the app.

I guess this is a security feature, so you don't forget about an app that has requested sensitive permissions.

According to the Android reference it should also be possible to completely remove the launcher icon. I wasn't able to make it work, but if I manage to do that, I could make a "light version" of the app without any icon.

**Comment by JonnyTech** [comment]
Fair comprompise - if nothing else, you squashed a bug. Thanks for the quick response, I shall leave this issue for you to close when you feel ready to.

**Comment by cvzi** [comment]
I am closing this as there is no indication that it will be possible to hide it again

Also for reference: I had reported the discrepancy in the documentation to Google but it has not been resolved: https://issuetracker.google.com/issues/155685106
