### ISSUE TITLE
keepAppDataMax's defaultValue is not unified

### ISSUE THREAD

**Issue by yfdyh000** [cvzi/ScreenshotTile#262]
The input box displays 20 but said that the default value is 30.

https://github.com/cvzi/ScreenshotTile/blob/aa1eaf169a1fd0232d096ebd7b9fcffb88a8b4d1/app/src/main/res/xml/pref_advanced.xml#L105
https://github.com/cvzi/ScreenshotTile/blob/aa1eaf169a1fd0232d096ebd7b9fcffb88a8b4d1/app/src/main/java/com/github/cvzi/screenshottile/utils/PrefManager.kt#L616
https://github.com/cvzi/ScreenshotTile/blob/aa1eaf169a1fd0232d096ebd7b9fcffb88a8b4d1/app/src/main/res/values/strings_advanced.xml#L33

**Comment by cvzi** [comment]
Thanks for the detailed report!
