### ISSUE TITLE
List as Voice Input?

### ISSUE THREAD

**Issue by OkyDooky** [cvzi/ScreenshotTile#266]
This is on Android 9 (stock) and I noticed that the assistant app [Dicio](https://github.com/Stypox/dicio-android) wasn't properly coming up as a voice input option for a translation app and, well, this was occupying that spot:
![Screenshot_2022-12-29_18-54-08](https://user-images.githubusercontent.com/59938024/210030010-14a495ae-74ce-4414-b1ff-6f7f13d697d2.png)
Dicio currently isn't even listed as an option, which is not this app's problem, but the fact that this is listed twice is kinda weird:
![Screenshot_2022-12-29_18-58-49](https://user-images.githubusercontent.com/59938024/210030062-61081ae3-1333-48f4-896f-0b7c7965d869.png)
Is this a side effect of it using the Assist App features listed in the othet issues? (And, for the record, I cannot select either of the other two options)
I don't think this is anything, major, but it seemed worth binging to your attention.

**Comment by cvzi** [comment]
Yes it is a side effect of the assist app feature.
It is because of a bug in Android 11 and lower. Basically any assist app is assumed to be a voice input as well by Android 11 and lower #190

No idea why it is listed twice though and why you can't select them

**Comment by cvzi** [comment]
It is normal that it appears twice and only one can be selected. Other assist apps also do this.
It is because the app offers a voice input service and an assist app service. 
(The voice input service of this app does nothing, but it necessary that it exists because of that bug #190)

It seems that the second entry can be renamed. Google's own assist app is listed twice as well, but with different names Google Assistant and Google Voice Recognition. I should try to rename the second entry to something like "Do not select this"

**Comment by cvzi** [comment]
I wonder if this app could do it the way Dicio is doing it at the moment. What they are doing "wrong" could be the right way for this app 😂

**Comment by OkyDooky** [comment]
Lol, lmao. That's the friendliest burn I've read in a while. "Your bug is my feature." XD Haha!
That makes more sense then. I thought it was some weird duplication thing going on, but if you can make one "disappear" or simply rename it to let users know what it does/doesn't do, or something making it clearer, that would be a good fix, I think.

**Comment by cvzi** [comment]
I've taken a look on how they do it.

With the current method of my app, when you start the assistant, Android immediately takes a screenshot and then delivers it to my app.
With Dicio's method, when you start the assistant, Android just starts the app. Then the app would have to take a screenshot itself, which is possible but would take longer.

Dicio's method does avoid the speech recognition bug on Android 11 and lower. 

But I don't really want to implement something inferior for the already two year old Android 11.

I'll stick with the current method and add a "do not select this" label to the selectable entry.

**Comment by OkyDooky** [comment]
Yeah, if it would make a noticeable difference in reaction time, then using a label would be best.
