### ISSUE TITLE
Request for a separate Application:

### ISSUE THREAD

**Issue by JagdishKumar1970** [cvzi/ScreenshotTile#27]
Hello, 

I'm a highly impressed, but non-Coder user of you Application(ScreenshotTile).
But I'm(and might be many more) also very resource conscious despite having a z2_plus(4,64,SD820), 
So i request you for a new Application if you agree.

Thank you; 

…continued in next comment!

**Comment by JagdishKumar1970** [comment]
Application: 
Name: 'AndroCrucial-Trinity'; 
Short Name: 'ACT'; 
ID: 'pkg.cvzi.act';

**Comment by JagdishKumar1970** [comment]
Basically it should be a extremely lite and basic edition((here)fork) of https://github.com/rascarlo/PowerButtonTile and https://play.google.com/store/apps/details?id=org.sugr.volumetile

**Comment by cvzi** [comment]
I will look into it. I have been thinking about making a lite version of my app for some time.

Could you a make list with the features that you would like?
