### ISSUE TITLE
Fake lossless webp.

### ISSUE THREAD

**Issue by z0cMWWKmGfudsDG** [cvzi/ScreenshotTile#296]
Choose the screenshot format as WEBP(lossless), then take a screenshot.
Use “webpinfo” command in [libwebp library](https://developers.google.com/speed/webp/download) to test, you will find that is lossy.
You can also observe the detail of picture. Lossy webp has obvious feature at colorful text with single color background. Halation.
Version:v2.0.8

**Comment by cvzi** [comment]
What is the Android version of your phone?

**Comment by z0cMWWKmGfudsDG** [comment]
> What is the Android version of your phone?

Android 8.1.0

**Comment by cvzi** [comment]
I see the problem. Android 8 doesn't natively support generating lossless WebP, so it shouldn't even offer Lossless as an option.

Could you check what it display in the advanced settings:
Set it to "Webp (lossless)" then scroll down to the bottom of the settings and open the advanced settings. There should be a "File format quality" entry. Below it should be a gray text indicating the actual format that is used. Could you check what it says? 

Thanks for your help!

**Comment by z0cMWWKmGfudsDG** [comment]
> Could you check what it says?

“WEBP (Lossy 100%) (Default: WEBP (Lossy 100%))”

**Comment by cvzi** [comment]
Thanks!

A quick search didn't yield any results for an easy-to-use library that can compress to lossless WebP on Android 9 and lower.

I don't want to spend too much time on this old Android version, so I'll just remove the Lossless option for Android 9 and lower. It is natively supported by Android 10+
