### ISSUE TITLE
Tile is always on

### ISSUE THREAD

**Issue by linsui** [cvzi/ScreenshotTile#3]
![screenshot_2019-03-08_20-08-25](https://user-images.githubusercontent.com/36977733/54028059-a3e8d100-41de-11e9-9b18-ea8aa79e82a3.png)

Cou it be off afer screenshot?

**Comment by cvzi** [comment]
I have not really thought about this yet. Currently the tile should be on if the permissions to take a screenshot are available (that was just useful for debugging).

So would you like it to be always off, and only on if you just clicked on it? I personally don't really care.

**Comment by linsui** [comment]
Yeah, I would like it to be always off :joy:

**Comment by cvzi** [comment]
Ok, in the next version will be always off.  Commit: 30235c23e91d09a40e84390524190e83eb3e0175

**Unrelated:**
I added an icon to the launcher, so if someone clicks the icon there is now a little tutorial.
Could you maybe translate these new strings:
```xml
<string name="hide_app_from_launcher">Hide app icon from launcher</string>
<string name="toggle_app_icon_failed">Failed to show/hide app icon</string>
<string name="tutorial">Tutorial</string>
<string name="tap_for_next_step">Tap for next step</string>
```
And I also added some with Google Translate, may you can check if everything is correct:
[values/strings.xml](https://github.com/cvzi/ScreenshotTile/tree/master/app/src/main/res/values/strings.xml)
[values-zh-rCN/strings.xml](https://github.com/cvzi/ScreenshotTile/tree/master/app/src/main/res/values-zh-rCN/strings.xml)

![Screenshot_1552140694](https://user-images.githubusercontent.com/8470684/54072627-a9492880-427d-11e9-8c15-4552121de901.png)
![Screenshot_1552140701](https://user-images.githubusercontent.com/8470684/54072628-a9492880-427d-11e9-8232-b3daabc747c8.png)

**Comment by linsui** [comment]
Of course! And could you put the about into strings?

**Comment by cvzi** [comment]
Yes, done: 946b99d48881a9a0e58341ffc3167c5b5ff95a31

Thank you!
