### ISSUE TITLE
Photo Editor: option to override original file with edited file by default

### ISSUE THREAD

**Issue by Cwpute** [cvzi/ScreenshotTile#300]
When editing a screenshot you've just taken, the editor alwbys create a new file for the edited picture. To me, this is not the intended behavior.

When i edit a screenshot i've just taken, it's usually to edit out unnecessary parts of the picture or add context without which the screenshot wouldn't be understandable. So i'd expect the editor to always overwrite the previous screenshot with its newly edited version.

This could be an opt-in option as its not what others might want.

**Comment by cvzi** [comment]
I think I can add it as an opt-in option

**Comment by cvzi** [comment]
Next version will have an option to overwrite files by default:
![Screenshot](https://github.com/cvzi/ScreenshotTile_miscellaneous/raw/main/Screenshots_for_translators/Prevent%20locked%2C%20Overwrite%20files.png)

**Comment by cvzi** [comment]
Added in [v2.2.2](https://github.com/cvzi/ScreenshotTile/releases/tag/v2.2.2)
