### ISSUE TITLE
timestamp enquiry

### ISSUE THREAD

**Issue by sidmint** [cvzi/ScreenshotTile#315]
I wish to get filename as Screenshot_20220423-114235 but can't achieve it. I set the setting as
Screenshot_yyyyMMdd-HHmmss but failed.

Great app by the way, thank you.

**Comment by cvzi** [comment]
That's currently not supported. 
It is only possible to set to `Screenshot_%timestamp%` which results in
`Screenshot_2023-04-05_11-22-56`

**Comment by cvzi** [comment]
Please open again, if you actually wanted this implemented
