### ISSUE TITLE
everytime need allow

### ISSUE THREAD

**Issue by cobayashi7411** [cvzi/ScreenshotTile#367]
i can make screen shot with received intent from macrodroid apk ONLY when I allow it every time  on the screen with my finger. Is there a way how to solve it?

**Comment by cvzi** [comment]
If you have **Android 9 or higher**, you can try to enable the "Native method" in the first screen of the app, then it should only ask once to enable the "accessibility".
This uses the default screenshot function of your Android (the screenshot function by your phone manufacturer), so it doesn't allow customization like different storage folder.

But if you have **Android 11 or higher** you can additionally disable "Use system defaults" in the app settings, then the app uses its own screenshot function, and you can enable customization like storage folder again.
