### ISSUE TITLE
Feature request: Add a shortcut icon (similarly to Öffi) or an option to take a screenshot when opening the app 

### ISSUE THREAD

**Issue by 42triangles** [cvzi/ScreenshotTile#370]
This would be a workaround for devices where the key combo of power & volume down is difficult to do, but where other buttons can be bound to open other apps (in this case for the XCover 6 Pro)

**Comment by cvzi** [comment]
I'll close this for now, reply if this is still relevant

**Comment by blackholeearth** [comment]
You can add tiles to pulldown control panel

You can also add delay 3 5 seconds.
After you click the button, you can open the related app / page

![Screenshot_20231021-002515_Nova7](https://github.com/cvzi/ScreenshotTile/assets/7512105/2edc7833-c0fd-4358-99da-cdbdedbd5534)
