### ISSUE TITLE
[Feature Request] Long screenshot for Original/Legacy Method

### ISSUE THREAD

**Issue by Quantenzitrone** [cvzi/ScreenshotTile#373]
Similarly to the Longshot feature of ScreenMaster, a proprietary Application from the PlayStore.
Basically, take multiple screenshots and automatically stitch the resulting images together to one long screenshot.

**Comment by shuvashish76** [comment]
Duplicate of #19

**Comment by Quantenzitrone** [comment]
You're right, I misread and/or missinterpreted the other Feature Request.
