### ISSUE TITLE
[Feature] Hide toast message before new screenshot

### ISSUE THREAD

**Issue by Cwpute** [cvzi/ScreenshotTile#395]
After a first screenshot, if you want take another one frapidly after that, there is a high chance you'll end up with the pop-uo for the previous one taking some space on the second screenshot.

ScreenshotTile should automatically hide its own pop-ups before taking a new screenshot to prevent this.

**Comment by cvzi** [comment]
I think it is not possible to hide the popup reliably (Or I just didn't find a way to do it).

There is an option to disable them completely:
in the app settings scroll down to "Advanced settings" and then disable "Toast notifications for successful events"
