### ISSUE TITLE
Feature: sound notification but no pop-up

### ISSUE THREAD

**Issue by Cwpute** [cvzi/ScreenshotTile#431]
Since my request in issue #395 is not possible, i'd like a workaround.

I'd like to be able to take a screenshot, that triggers a confirmation sound, but no toast message or pop-up.
This way i'd be ableto take several screenshots in a row without having to wait between screenshots that the previous message disapears.

**Comment by cvzi** [comment]
I think that should be easy to add

**Comment by cvzi** [comment]
This is now possible by going to "Subsequent actions" on the main screen of the app: There you can de-activate the toast popup and enable playing a sound.

---

Note to myself:
In the sound selector only the text reacts to touch/click -> whole row should react.
