### ISSUE TITLE
Remove advertising for donation to israel

### ISSUE THREAD

**Issue by tiipi** [cvzi/ScreenshotTile#454]
The box appears on top in main activity.
Nothing is mentioned in changelog.
![ss-2023-10-26-11-56-31-404](https://github.com/cvzi/ScreenshotTile/assets/125903312/aa191c1c-2805-44a5-b914-2a2dd01ae3f0)

**Comment by cvzi** [comment]
It was added in 2.3.7 as mentioned in the Changelog

**Comment by tiipi** [comment]
The issue wasn't changelog.
Will have to make a fork or use older version, you probably knew that this was putting bloatware and an ad into the app.

**Comment by cvzi** [comment]
At the moment I am not planing to remove it.

**Comment by tiipi** [comment]
Already figured it out, jew
