### ISSUE TITLE
Delayed screenshot instantly taken on swipe

### ISSUE THREAD

**Issue by Cwpute** [cvzi/ScreenshotTile#465]
I tried to take a screenshot of the touchscreen keyboard in Unciv using ScreenshotTile, aut it wouldn't let me as the slishest swipe in any direction instantly triggers the delayed screenshot, as you can see below:
![screenshot00290](https://github.com/cvzi/ScreenshotTile/assets/80604512/673bdafe-306d-4116-888f-fb81ae3a014d)
You can even see ScreenshotTile's countdown timer in the middle as proof.

I thought this may only happen in Unciv, wr in landscape mode, but it seems it just triggers after a swipe:
![screenshot00293](https://github.com/cvzi/ScreenshotTile/assets/80604512/59d91b8e-f80d-4641-9be9-b829e1ada183)

Please make ut so it doesn't instantly triggers the screenshot on any swipe, or at least give us the opportunity to choose this behavior in the settings, to which gesture or action should the screenshot be taken.

**Comment by cvzi** [comment]
There is now an option in the settings to disable it
