### ISSUE TITLE
I'm using screen tile shot.

### ISSUE THREAD

**Issue by Viv007lov** [cvzi/ScreenshotTile#469]
HOW DO I SILENCE THE SCREENSHOT.  MY EMAIL ADDRESS IS vivianhunter214@gmail.com

**Comment by Viv007lov** [comment]
THANK you it worked.

**Comment by Viv007lov** [comment]
I did work where the sound to the screenshot was muted.  But the ability to
write on the screenshot was taken away.

BUT now I'm FORCED TO USE THE SCREEN SHOT TILE APP, WITH SOUND AFTER TAKING
A SCREENSHOT.

BECAUSE IF I TURN OFF System SETTING IN THE SCREENSHOT TILE APP, I CAN NOT
WRITE ON THE SCREENSHOT.

I USUALLY TAKE A SCREEN SHOT OF MY BANK BALANCE AND WRITE DOWN THE DATE ON
IT, TO KEEP TRACK OF MY BANKING BUDGET.

SO I GUESS IM STUCK WITH THE SCREENSHOT SOUND.

**Comment by cvzi** [comment]
If you have disabled "Use system defaults", then you can change the settings to open a photo editor after the screenshot:

Open the ScreenshotTile app and scroll down and press the button "Subsequent actions".
Probably it is set to "Do not open screenshot", you can change it to "Open included photo editor". This will open the screenshot image after you took it and you can write or draw on it immediately. 
You could also use "Open external photo editor" if your phone already has a photo editor installed.

**Comment by Viv007lov** [comment]
I tried doing it, but it didn't work.  But thank you for your help.  Now I
just put my phone  on, do " not disturb" , and take the screenshot without
sound.  Thanks anyway for all your help.

**Comment by cvzi** [comment]
In that case, maybe you can long press the screenshot notification that appears after the screenshot is taken and then set the notification to silent mode.

**Comment by Viv007lov** [comment]
Awesome, thanks for the update!
