### ISSUE TITLE
Not issue just Question:  scrreenshottile from shell command

### ISSUE THREAD

**Issue by pvdt41** [cvzi/ScreenshotTile#473]
Is it possible to take partial screenshot from command line so I can use it in exposed edge
I tried this

am broadcast -a com.github.cvzi.screenshottile.SCREENSHOT -e secret zz -e partial true com.github.cvzi.screenshottile

this takes screenshot but doesnt do the partial 

(zz is my password)

**Comment by cvzi** [comment]
I think it needs to be `--ez` because it expects a boolean value. 

```
am broadcast -a com.github.cvzi.screenshottile.SCREENSHOT -e secret zz --ez partial true com.github.cvzi.screenshottile
```

**Comment by pvdt41** [comment]
Yes its working.
Thank you very much cvzi.
