### ISSUE TITLE
Screenshot capture not working after changing to different filename format

### ISSUE THREAD

**Issue by EthicalGhost** [cvzi/ScreenshotTile#480]
Screenshot capture is not working when I change default filename format to "Screenshot_%random%" or any other format other than the default one.
I have set it as Assist app. I have even tried it after a reboot, force-stop etc. but no luck so far.
My device is a Samsung Galaxy running on Android 11.

Edit: I forgot to add, after changing to "Screenshot_%random%" if you revert to the default "Screenshot_%timestamp%", it still does not work.

**Comment by cvzi** [comment]
Sorry I must have overlooked this

**Comment by cvzi** [comment]
Should be fixed now
