### ISSUE TITLE
No camera sound after changing file format to WebP (95% lossy)

### ISSUE THREAD

**Issue by NeanderthalNinny** [cvzi/ScreenshotTile#488]
I changed the File format to WebP (95% lossy) which does an excellent job at image compression, but now the nice default camera sound no longer plays after taking a screenshot 😕

I have enabled the "play sound" option under "subsequent actions" but cannot find the audio tone for the default sound. How can I enable the default camera sound? Where is the camera click sound located? 

I'm using a Pixel 8 Pro android phone. 

Thank you for this excellent software 😀

**Comment by cvzi** [comment]
It's not possible at the moment. 

That default sound is not played by this app. This app actually just asks the default screenshot app of Android to take a screenshot, and then the default screenshot app handles everything: takes the screenshot, stores the file, shows a notification and plays the default sound. 

Now if you select some custom settings (like file format), then this app does take the screenshot itself and doesn't use the default screenshot app at all. Consequently there is no default sound played.

The list of sounds that is currently available are some default Android sounds that are included on all Android devices, so they were easy to add for me.
In theory I could also add an option to select a custom sound from the ringtone selector or from an mp3 file, but at the moment that is not possible.

**Comment by NeanderthalNinny** [comment]
No problem. Thank you for the detailed explanation.
Keep up the good work

NN
