### ISSUE TITLE
Sometimes it fails

### ISSUE THREAD

**Issue by linsui** [cvzi/ScreenshotTile#5]
It will show notification as normal but in fact it fails to take a screenshot. And I will get `Error: Album null` if I tap on the notification. There will be a black picture in album. My rom is Pie.

**Comment by cvzi** [comment]
Do you remember if the little thumbnail image on the notification was shown?
And do you know if the problem has happened before or only on the newest version?

**Comment by linsui** [comment]
I found the `Error: Album null` was caused by system. I reboot and it disappeared. Now the problem is sometimes it takes an all black screenshot. If it fails, no thumbnail image on the notification is shown. And it takes a little longer time when successes than it fails. I have a try on 1.24 and 1.32 but I don't know when it successes or fails.

**Comment by cvzi** [comment]
So sometimes there is an actual image file saved but it is completely black?

**Comment by linsui** [comment]
Yes. 
![Screenshot_2019-04-10_08-10-00](https://user-images.githubusercontent.com/36977733/55843342-63c49780-5b6a-11e9-900c-34f96eb9aa8b.png)

**Comment by linsui** [comment]
Now it doesn't work at all... I always get an empty image.

**Comment by nostromov** [comment]
LOL, I'm staring at "actual image file saved but it is completely black" and trying to figure out what's wrong, with the image. Tz, tz. :) 

*behold: https://ibb.co/rFzz2cR

**Comment by sengsational** [comment]
The app works when the foreground app hasn't blocked screen shots, but if the foreground app has precluded screenshots, I get a black image.  Of course the whole reason to install this app is to get a screenshot in the case where the app you're viewing has the screen capture blocked!  So although I appreciate that some users might find the tile handy, I'd rather not have an extra app and simply use the hardware button sequence (concurrent volume-down + power).

**Comment by cvzi** [comment]
Thank you for the explanation. I see this is a "security" feature of Android. 
I close this issue as their is/should be no way to circumvent this (without root access).
