### ISSUE TITLE
[Feature] Allow ScreenshotTile "Special access" (Samsung)

### ISSUE THREAD

**Issue by ElsAr4e** [cvzi/ScreenshotTile#529]
It should be possible to make screenshots of apps where you get the error message "Can't Take Screenshot Due to Security Policy" if you have the option “All files access” on (non-rooted) Samsung phones.

https://www.samsung.com/uk/support/mobile-devices/how-to-solve-screenshot-errors-on-devices-with-android-13-os/

https://drfone.wondershare.com/android-problems/can-not-take-screenshot-due-to-security-policy.html

Until now I was not able to check that option using ScreenshotTile. Could you make it possible that ScreenshotTile gets an option to appear on the list of Special access > All files access so that you can make screenshots of protected apps?

**Comment by cvzi** [comment]
Maybe I can make an extra .apk-file for you to try. 

But this permission is not allowed on the Google Play Store except for file managers so I can't add it to the normal app.

**Comment by ElsAr4e** [comment]
> But this permission is not allowed on the Google Play Store except for file managers so I can't add it to the normal app.

But F-Droid would allow to publish an app with this permission?

Anyway thanks for the answer (and the extra .apk file?)!

**Comment by cvzi** [comment]
F-Droid would allow it, but let's wait if this even works.

I can't find anything about whether this in the android documentation, so I don't know how to to apply it. But the documentation is notoriously incomplete and outdated when it comes to this permission. 

Maybe it is enough to only add the permission and no other code changes. This would be just a few lines of code. I can probably try it tomorrow.

**Comment by ElsAr4e** [comment]
> I can probably try it tomorrow.

Do you also have a Galaxy device?

I'm just not sure - the links says Android 13. I am using Android 14. - So not sure if this works just for Android 13 or for Android 13+.

And I can't install Samsung Capture - I get the error "Device isn't compatible with this app" so I can't try.

**Comment by ElsAr4e** [comment]
Just tried and it does not work.

Not sure if it does not work because I am not using Android 13 but Android 14 or if the OS of Samsung also checks if it's their own app?

Is One UI 6.0 actually open source and you could check what "special access" means?

----

So the only way to capture screenshots of apps that show "Can't Take Screenshot Due to Security Policy" is to patch the apk and disable / remove the Flag Secure module or use Virtual Android on non-rooted phones?

**Comment by cvzi** [comment]
I tried on the Android emulator (which is similar to a Google Pixel) with Android 13 and 14 and it doesn't work there either.

> Not sure if it does not work because I am not using Android 13 but Android 14 or if the OS of Samsung also checks if it's their own app?

I think because it is a system app, it can also take screenshots in a different way than normal apps. 

> Is One UI 6.0 actually open source and you could check what "special access" means?

It looks like some parts are open source, but nothing related to this.

I did look into the Samsung Capture app. I downloaded a Samsung Capture apk file and looked at the source code, but it is partially obfuscated and I didn't find anything helpful.

> So the only way to capture screenshots of apps that show "Can't Take Screenshot Due to Security Policy" is to patch the apk and disable / remove the Flag Secure module or use Virtual Android on non-rooted phones?

I am not aware of an "official" way to do it. It is a security feature, so it makes sense that you can't circumvent it easily.

**Comment by ElsAr4e** [comment]
You can make take screenshots of protected apps using Virtual Android on non-rooted devices: https://play.google.com/store/apps/details?id=com.pspace.vandroid

Or you would need a (non-rooted) modified OS: https://github.com/GrapheneOS/os-issue-tracker/issues/664

----
But anyway: Have you been able to take a screenshot of protected apps (maybe there is a Samsung emulator) using Samsung capture?

**Comment by cvzi** [comment]
No, Samsung Capture doesn't work for me, I guess it only works on Samsung devices. There is no emulator or emulator images for Samsung's Android (at least not for free, maybe there are paid services).
