### ISSUE TITLE
[Request] Option to hide floating button in landscape mode

### ISSUE THREAD

**Issue by emvaized** [cvzi/ScreenshotTile#533]
Hi there! 
I placed my floating button for taking screenshot in the bottom right corner of the screen, so that it looks like a navbar button. 

However, when the screen rotates to the landscape mode, the button is shifted to the bottom center of the screen. Given my usage scenario, I would like to don't show it at all in the landscape mode... Could you please consider adding such an option to floating button settings?

**Comment by cvzi** [comment]
I can probably add that

**Comment by emvaized** [comment]
> I can probably add that

It would be great! Thanks a lot

**Comment by cvzi** [comment]
The new version has an option the floating button settings to disable it. Also it now stores a separate location for the floating button for portrait orientation and for landscape orientation.

**Comment by emvaized** [comment]
Super great! Many thanks 🙏
