### ISSUE TITLE
Screenshots taken in landscape with Samsung Tablet process incorrectly

### ISSUE THREAD

**Issue by Starcr0ss** [cvzi/ScreenshotTile#556]
I have a Galaxy Tab A (2019, SM-T510) with Android 11. Taking screenshots in landscape produce distorted images. I take screenshots using the "hold the home button" / assistant method.
An example screenshot is attached below:
![Screenshot_2024-08-01_21-42-19](https://github.com/user-attachments/assets/a75957fb-18de-4d08-84d6-8281d45653fc)

**Comment by cvzi** [comment]
Seems to affect Android 10 as well, but not Android 9 and 12+

**Comment by cvzi** [comment]
This is a bug in the assistant mode in Android 10 and 11. The screenshot is distorted by Android, so the app can't fix it. I'll add a permanent work around for this.

The current workaround is to set the assistant action to "Use native screenshot method", this will use a different way to take the screenshot and avoid the bug:

* Open the app, go to "More settings"
* Find the setting "Assistant action"
* Set it to "Use native screenshot method"
* You should be redirected to the accessibility settings, where you have to enable the app (if you haven't done this previously)

By default this will use the phone's screenshot app (in your case Samsung screenshot tool) to take the screenshot. You can change that behavior by disabling the setting "Use system defaults".

**Comment by cvzi** [comment]
Since version 2.11.1 the app uses the work-around on Android 10 and 11 if the accessibility service is running. Otherwise it shows a warning about this bug and suggests to enable the accessibility service.
