### ISSUE TITLE
The position of screenshot button will be reset sometimes 

### ISSUE THREAD

**Issue by Kyant0** [cvzi/ScreenshotTile#562]
I have met many times, the button will go to the top-left.

**Comment by cvzi** [comment]
Does this happen randomly or when you do something specific?

**Comment by Kyant0** [comment]
It happens randomly

**Comment by cvzi** [comment]
There was similar issue on Android 14 and I thought I fixed it, but maybe it is not completely solved.

What phone do you use and what's the Android version?

**Comment by Kyant0** [comment]
Google Pixel 4XL, Android 13

**Comment by cvzi** [comment]
In the newest version the app tries to restore the position periodically. Maybe that helps, I am not sure.

I couldn't reproduce the problem on other phones, I didn't have a Pixel 4XL for testing though.

**Comment by Kyant0** [comment]
Good news, it won't happen any more as of this time
