### ISSUE TITLE
Request to remove the advertisement

### ISSUE THREAD

**Issue by shuvashish76** [cvzi/ScreenshotTile#565]
![Screenshot_2024-08-16_03-41-19_1](https://github.com/user-attachments/assets/6c7142fc-3a1a-42ca-a669-c3f02b95ae4e)

Request to remove the ad.
See Ads AF: https://f-droid.org/en/docs/Anti-Features/#Ads
Originally posted on F-Droid forum: https://forum.f-droid.org/t/screenshot-tile-annoying-ad/26770

**Comment by cvzi** [comment]
You can just click the little x icon to remove it

**Comment by cvzi** [comment]
Oh I see the problem, I'd rather add the anti-flag badge than remove the donation links though. But I think this needs to be done at http://gitlab.com/fdroid/fdroiddata/, I don't think I can add it myself

**Comment by shuvashish76** [comment]
> You can just click the little x icon to remove it.

Yes it's one time only.

According to the reporter the app should get Ads AF for this. So I created for the clarity on this topic.
@linsui @vdbhb59 I'm not sure if such donations option to any service/cause _other than for your project_ considered as Ads as well. Will be an ad if you show donation option for e.g. F-Droid or FSF ?

Though this ad doesn't tries to persuade the users it's still a banner ad that promotes its political interests.

**Comment by cvzi** [comment]
I have created an issue at fdroiddata: https://gitlab.com/fdroid/fdroiddata/-/issues/3335

**Comment by shuvashish76** [comment]
> I'd rather add the anti-feature badge than remove the donation links

My original request still remains...if you remove the banner in future please make a MR at F-Droid for this.
I think now it matches to F-Droid Ads AF, since you mentioned "the banner _links to some **unrelated** NGOs_". Closing thanks.
