### ISSUE TITLE
Telegram and photo of the page

### ISSUE THREAD

**Issue by Kingrad1** [cvzi/ScreenshotTile#579]
greetings to you  Unfortunately, it is not possible to take pictures of Telegram pages that do not allow taking pictures. If you can do this, it would be great.   Thank you again for your good program and good luck. 🙏

**Comment by cvzi** [comment]
Unfortunately it is not possible with "normal" apps to take such screenshots. You would need root-access (super user) to circumvent the protection (I don't use root-access myself and so I don't want to support it). I think some custom ROMs also allow to circumvent it, but I don't know exactly which ones or if this is still true today.
