### ISSUE TITLE
Tile Disappears After Restart

### ISSUE THREAD

**Issue by puppykickr** [cvzi/ScreenshotTile#6]
The app works great, but every time I restart my device, the tile disappears, and I must edit the quick setting tiles again in order to put the tile back on the quick settings menu.

**Comment by cvzi** [comment]
Ok that's not supposed to happen. 

Can you provide your Android version and your phone model (and ROM if you know it).
I think this might be a device specific problem.

**Comment by puppykickr** [comment]
Android 8.1.0
Poblano VLE5  Android Go

I concur that it may very well be device specific, as I also have the app on a 7.1.1 and the issue does not seem to occur there.

I am not sure, however, as that
device rarely needs to be restarted.

With the limited capability of the Poblano, restarts occur rather often.

Usually about every 2-3 days.

**Comment by cvzi** [comment]
I have not found any way to reproduce this. 
It might help to automatically start the app (service) after every boot. I created two .apk files that you can test:
[screenshottile.zip](https://github.com/cvzi/ScreenshotTile/files/3073744/screenshottile.zip)
If either solves the problem, I can include it in the published app.

The difference is:
_screenshottile-debug_background.apk_ (9c4debc47d9ccc16811df0521979b0393a67d7ab) starts the service in the background after reboot and
_screenshottile-debug_foreground.apk_ (66c7fcd936684fefb0dce0ad492d0cc7539893f5) starts the service in the foreground after reboot with a notification

**Comment by puppykickr** [comment]
I really think that it is the device.

I base this on the fact that I have found this to also occur with other apps as well.

It seems that the same thing occurs with any aftermarket app that has a quicksetting tile.

I am just screwed with this on this device.

But, on my 7.1.1 devices, this app is Godsend, as the power and volume buttons are almost non-functional on both.

**Comment by puppykickr** [comment]
Thank you for the other versions.
I will try them out when I have tvhe chance.

I think I might have found the issue--  the device in question has only 1GB RAM, and so I formatted the SD card as internal rather than external (mostly as an experiment).

I checked, and sure enough, your app was on the external memory rather than the internal.

I have moved it to the internal, and will let you know what happens with the tile, the next time I reboot the phone.

**Comment by puppykickr** [comment]
Guess what?
Last night, I had to restart my 8.1.0
This is the device that the tile(s) disappear from when the device is restarted.

Well, I had moved the app to the internal memory, and now the tile does not disappear when the device is restarted.

Sorry to have put you through this, but it has been a while since I have had to deal with a 1GB device, so I forgot all about little quirks like this that occur when an app is on external rather than internal memory.

Luckily, the app is so small that there is no real reason to have it on the external.

If you like, I can still test out the other versions that you provided, on both my 7.1.1 (internal only) and my 8.1.0 (external and internal).

**Comment by cvzi** [comment]
Thanks for report. No need to test the other versions, they can't solve that problem.

I am gonna check if I can somehow prevent people from installing the app on external memory, I think there was a way to do that. Otherwise I'll state it in the app store description.

**Comment by puppykickr** [comment]
Really, it is probably not an issue.

This 1GB phone is a rarity nowadays, and the only reason that the app went to the SD card is that I formatted the card as internal rather than external memory, and have the developer options set to put any app on the card.

It was done as an experiment, to find the advantages and disadvantages of doing that.

Most people only choose to use a card as external memory, and apps will still go onto the internal memory. (Even with the developer options set to put apps on the card.)

I just had forgotten all about how little things change (like tiles) when restarting a phone with apps on a SD card.
