### ISSUE TITLE
[Feature Request] Editing the photo on the go

### ISSUE THREAD

**Issue by tuekacode** [cvzi/ScreenshotTile#64]
When you already take the screenshot, you got directed to the edit section of the app where you can crop or add some drawing. You can see the example here :
https://play.google.com/store/apps/details?id=com.jbs.util.takescreen&hl=en_US&gl=US

**Comment by cvzi** [comment]
I will check if there are any open source photo editor libraries that could be used.
Programming this from scratch would be a lot of work and any photo editor app can already do it.

**Comment by cvzi** [comment]
I think it would be possible to directly open another image editor app with the screenshot file after a screenshot was taken.

Then there could be an option in the settings:

Action after screenshot
 * Show notification
 * Do nothing
 * Open app XY to edit image

**Comment by cvzi** [comment]
Thanks I will check it out

**Comment by cvzi** [comment]
This library seems to be very easy to add, but it doesn't have a crop/scale function 😐

**Comment by cvzi** [comment]
I will try to add the library anyway. It doesn't seem to be easy to add a crop function into that library but maybe I can add a separate crop function to the app

**Comment by cvzi** [comment]
New release: [v2.0.0-beta1](https://github.com/cvzi/ScreenshotTile/releases/tag/v2.0.0-beta1)


![Subsequent_actions_activity](https://user-images.githubusercontent.com/8470684/186343222-7f84fc09-d7f3-4054-9fb2-bc581f497535.png)
