### ISSUE TITLE
[FR] Select area to capture

### ISSUE THREAD

**Issue by mtbu** [cvzi/ScreenshotTile#9]
On LOS 14.1, long-pressing the screenshot option in the power menu allows taking a screenshot of only a chosen area of the screen (selected at that time). This would be a nice feature to have in this app (could be accessed in the long-press menu with the delay options) unless it would add too much complexity.

**Comment by cvzi** [comment]
It sounds interesting. I am not sure how complex it is.
I checked LOS and it looks like this is the code they use, so maybe I can get some inspiration from that
[LineageOS/android_frameworks_base/packages/SystemUI/src/com/android/systemui/screenshot/](/LineageOS/android_frameworks_base/tree/lineage-16.0/packages/SystemUI/src/com/android/systemui/screenshot)

**Comment by cvzi** [comment]
The new version 1.6.0 has a first attempt. In the long-press menu there is now the new option.
I don't think I am gonna use it much myself, so if you can, please test it and give me feedback or suggestions
